version: '3'

services:
  app:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:s3cr3t@postgres:5432/demo_app?pool=5&timeout=5000
    volumes:
      - .:/app
    links:
      - postgres
    ports:
      - "5000:5000"

  postgres:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: s3cr3t
      POSTGRES_DB: demo_app
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgresql_data:
