name: Build and Push to ECR
on:
  release:
    types:
      - created

env:
  AWS_REGION: sa-east-1
  ECR_REPOSITORY: agrosmart/agrosmart-api

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set tag var
        id: vars
        run: |
          echo ::set-output name=version::$(echo ${{ github.ref }} | cut -d'/' -f3 | tr 'v' ' ')
      - name: Show tag var
        run: |
          echo ${{ steps.vars.outputs.version }}
